---
title: "about.Rmd"
author: "Vivian Zhang"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I am interested in studying remittance flows among EU member states, looking into how the free movement of people has affected remittance trends. In my gather.Rmd file, I have 4 main clusters of data. First, I have a code chunk for the usd data set, which lists out the quantity of remittance flows in US dollars in a given EU country in a given year. I also have a code chunk that generates a table showing the percentage of GDP that each country's remittance flow represents in a given year. The remittance_inflows looks at the quantity of remittances flowing into each country in a given year. Finally, the bilateral remittance matrices how much each EU country is sending in remittances to other countries around the world. I chose to keep each year's data distinct for now so that I can later create an interactive map graphic that automatically cycles through the years, showing flows for each year. All of these data sets come from the World Bank website, which offered excel documents to download. For the EU countries, the data is relatively complete. I also scraped a table with information on the EU and its member states from Wikipedia and used the list of country names to play with the other data I had.

<a href=https://github.com/VivianZ101055/final_project.git> Link to my repo </a>