---
title: "final_project"
author: "Vivian Zhang"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(janitor)
library(rvest)
library(magrittr)
library(base)
library(reshape2)
library(shiny)
# library(ggmap)
# library(mapproj)
# library(rworldmap)
# library(rworldxtra)
library(leaflet)
library(tidyverse)

```

```{r}

# I went to a session at the ARC to ask about strategies
# to approach the final project.
# I learned that on top of seeing the final html files of past projects, I could
# see how students implemented their code through a github link on each website.
# After looking through half a dozen projects, I have a better idea for what I
# want to do in terms of formatting. In particular, this map of Latin America
# interests me. I want to display remittance inflows and outflows by having a
# button on top of each country that allows the user to click and see how much
# inflow or outflow there was.
# https://igormorzan.shinyapps.io/Latin_American_Corruption/

```

```{r member states}

eumemberinfo <- read_html('https://en.wikipedia.org/wiki/Member_state_of_the_European_Union', skip = 0)

eumemberinfo <- eumemberinfo %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table[5]') %>%
  html_table()

eumemberinfo <- eumemberinfo[[1]]

# Removing Wikipedia annotations

eumemberinfo$Name <- str_remove_all(eumemberinfo$Name, "\\[.*\\]")

# Changing the names because Eastern European countries are labeled
# differently on the two datasets

eumemberinfo$Name[eumemberinfo$Name == "Czechia"] <- "Czech Republic"

eumemberinfo$Name[eumemberinfo$Name == "Slovakia"] <- "Slovak Republic"

name <- eumemberinfo %>% 
  select(Name) 

names(name) <- c("sender")
  
```

```{r dataset, include=FALSE}

# Load remittances in USD in a given country, in alphabetical order

usd <- read_excel("data/remittances_usd.xls", skip = 3)

# Trying to get rid of the x in front of the data
# Filter to only show between 1980 to present
# Repeatedly getting the error that argument "pattern" is missing, with no
# default
# Convert USD to Euros - maybe later

usd <- usd %>%
  pivot_longer(
    cols = `1980`:`2018`,
    names_to = "year",
    names_prefix = "yr"
               )

usd <- usd[,-c(5:25)]

# join this with the eumemberinfo to only look at member states

full_data <- usd %>%
  inner_join(eumemberinfo, by = c("Country Name" = "Name")) %>%
  rename(remittances_in_usd = value) %>%
  clean_names %>%
  filter(country_name %in% name$sender)

# Load remittances as percentage of GDP for a given country

percent_gdp <- read_excel("data/remittance_percentgdp.xls", skip = 3)

percent_gdp <- percent_gdp %>%
  pivot_longer(
    cols = `1980`:`2018`,
    names_to = "year",
    names_prefix = "yr") %>%
  rename(remittances_percent_gdp = value) %>%
  clean_names %>%
  filter(country_name %in% name$sender)

percent_gdp <- percent_gdp[,-c(5:25)]

# Join this with the previous data and select only the relevant columns

full_data <- full_data %>%
  inner_join(percent_gdp, by = c("country_name"="country_name", "year"="year"), suffix = c("_usd", "_gdp")) %>%
  select(country_name, country_code_usd, accession, year, remittances_in_usd, remittances_percent_gdp)

```

```{r remittance inflows}

# Load remittance inflows

remittance_inflows <- read_excel("data/remittance_inflows.xlsx", skip = 0)

# Pivot years into column, clean names, rename columns
# Filter for EU countries, remove columns

remittance_inflows <- remittance_inflows %>%
  pivot_longer(
    cols = `1980`:`2018`,
    names_to = "remittance_inflows",
    names_prefix = "yr") %>%
  clean_names %>%
  rename(remmitance_inflows=value, year=remittance_inflows, country_name = migrant_remittance_inflows_us_million) %>%
  filter(country_name %in% name$sender) %>%
  select(-c(x2019e, remittances_as_a_share_of_gdp_in_2019_percent))

# Join into full dataset

full_data <- full_data %>%
  inner_join(remittance_inflows, by = c("country_name"="country_name", "year"="year"))

# <- data[ -c(19:22) ] %>%
# na.omit()

```

```{r bilateral remittance 2010}

brf_2010 <- read_excel("data/BilateralRemittanceMatrix2010.xlsx", skip = 1) %>% 
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2010)

names(brf_2010) <- c("sender", "recipient", "amount", "year") 

brf_2010 <- inner_join(name, brf_2010, by = "sender")

```

```{r bilateral remittance 2011}

brf_2011 <- read_excel("data/BilateralRemittanceMatrix2011.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2011)

names(brf_2011) <- c("sender", "recipient", "amount", "year") 

brf_2011 <- inner_join(name, brf_2011, by = "sender")

```

```{r bilateral remittance 2012}

brf_2012 <- read_excel("data/BilateralRemittanceMatrix2012.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2012)

names(brf_2012) <- c("sender", "recipient", "amount", "year") 

brf_2012 <- inner_join(name, brf_2012, by = "sender")

```

```{r bilateral remittance 2013}

brf_2013 <- read_excel("data/BilateralRemittanceMatrix2013.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2013)

names(brf_2013) <- c("sender", "recipient", "amount", "year") 

brf_2013 <- inner_join(name, brf_2013, by = "sender")

```


```{r bilateral remittance 2014}

brf_2014 <- read_excel("data/BilateralRemittanceMatrix2014.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2014)

names(brf_2014) <- c("sender", "recipient", "amount", "year") 

brf_2014 <- inner_join(name, brf_2014, by = "sender")

```

```{r bilateral remittance 2015}

brf_2015 <- read_excel("data/BilateralRemittanceMatrix2014.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2015)

names(brf_2015) <- c("sender", "recipient", "amount", "year") 

brf_2015 <- inner_join(name, brf_2015, by = "sender")

```

```{r bilateral remittance 2016}

brf_2016 <- read_excel("data/bilateralremittancematrix2016.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2016)

names(brf_2016) <- c("sender", "recipient", "amount", "year") 

brf_2016 <- inner_join(name, brf_2016, by = "sender")

```

```{r bilateral remittance 2017}

brf_2017 <- read_excel("data/bilateralremittancematrix2017.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2017)

names(brf_2017) <- c("sender", "recipient", "amount", "year") 

brf_2017 <- inner_join(name, brf_2017, by = "sender")

```

```{r}
# Filter for only EU member states
# Clean data so we don't have so many 0.0000000e's and have 0's instead
# Current columns are remittance-receiving countries
# IMPORTANT: How do I get the 2012 label to show up
# Is there a less redundant way to do this
# Finally is to flip the axis the other way, so I can see when
# EU members are senders

mytempdata <- inner_join(brf_2010, brf_2011, by = "sender", suffix = c("_2010", "_2011"))

mytempdata <- inner_join(mytempdata, brf_2012, by = "sender", suffix = c("_2011", "_2012"))

mytempdata = merge(mytempdata, mydata3)

```

```{r rbind}

all_bilateral_remittance <- rbind(brf_2010, brf_2011, brf_2012)

```

```{r map plot}

# # All data loaded. Next, map showing the remittances in USD.

# Using Leaflet, an open-source Javascript library
# to create an interactive map

qpal <- colorQuantile("Blues", full_data$remittances_in_usd)

ui = fluidPage(
  sliderInput(inputId = "year", "Year", 1980, 2018, value = 2010), leafletOutput(outputId = "map")
)

server = function(input, output) {
  output$map = renderLeaflet({
    leaflet() %>%
      addPolygons(data = full_data[full_data$remittances_in_usd])
  })
}

# shinyApp(ui, server)

euromap <- leaflet() %>%
  addTiles() %>%
  setView(30, 55, 3)

addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1, color = ~qpal(full_data$remittances_in_usd)) %>%
qpal <- colorQuantile("Blues", full_data$remittances_in_usd)

euromap <- euromap %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1, color = ~qpal(remittances_in_usd))

euromap <- euromap + geom_sf(aes(fill = remittances_in_usd))
  geom_sf(aes(fill = remittances_in_usd)) +
  scale_fill_viridis_c(option = "plasma")


locationmode = "country_name") %>%
  add_trace(z= ~remittances_in_usd, locations = ~country_name, color= ~remittances_in_usd, colorbar=list(tick0 = 0, tickmode = "log", dtick=1000000))

full_data

```

