---
title: "Milestone 3"
author: "Vivian Zhang"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(janitor)
library(rvest)
library(magrittr)
library(base)
library(reshape2)
library(plyr)
library(tidyverse)

```

```{r member states, include=FALSE}

eu_members <- read_html('https://en.wikipedia.org/wiki/Member_state_of_the_European_Union', skip = 0)

eumemberinfo <- eu_members %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table[5]') %>%
  html_table()

eumemberinfo <- eumemberinfo[[1]]

# Removing Wikipedia annotations

eumemberinfo$Name <- str_remove_all(eumemberinfo$Name, "\\[.*\\]")

# Changing the names because Eastern European countries are labeled
# differently on the two datasets

eumemberinfo$Name[eumemberinfo$Name == "Czechia"] <- "Czech Republic"

eumemberinfo$Name[eumemberinfo$Name == "Slovakia"] <- "Slovak Republic"

name <- eumemberinfo %>% 
  select(Name)

names(name) <- c("sender")

name_country <- eumemberinfo %>% 
  select(Name) 

names(name_country) <- c("country_name")
  
```

```{r usd dataset, include=FALSE}

# Load remittances in USD in a given country, in alphabetical order
# Created an entry for each country in the EU, for each year, making note
# of the amount of remittance flow in US dollars
# This data comes from the World Bank Website:
# https://www.worldbank.org/en/topic/migrationremittancesdiasporaissues/brief/migration-remittances-data

usd <- read_excel("data/remittances_usd.xls", skip = 3) %>%
  select(-c("Indicator Name", "Indicator Code", "Country Code")) %>%
  melt(id.vars = "Country Name") %>%
  mutate(year = as.numeric(variable) + 1959) %>%
  filter(year >= 1980) %>%
  clean_names() %>%
  select(-c(variable))

usd <- inner_join(name_country, usd, by = c("country_name"))
names(usd) <- c("country", "remittances_in_usd", "year")

```


```{r percent_gdp, include=FALSE}

# Created an entry for each country in the EU, for each year, making
# note of the amount of remittance flow relative to each
# member state's GDP
# This data comes from the World Bank Website:
# https://www.worldbank.org/en/topic/migrationremittancesdiasporaissues/brief/migration-remittances-data

percent_gdp <- read_excel("data/remittance_percentgdp.xls", skip = 3) %>%
  select(-c("Indicator Name", "Indicator Code", "Country Code")) %>%
  melt(id.vars = "Country Name") %>%
  mutate(year = as.numeric(variable) + 1959) %>%
  filter(year >= 1980) %>%
  clean_names() %>%
  select(-c(variable))

percent_gdp <- inner_join(name_country, percent_gdp, by = "country_name")
names(percent_gdp) <- c("country", "remittance_percent_of_gdp", "year")

# full_data <- usd %>%
#   inner_join(percent_gdp, by = c("country"))
```


```{r remittance inflows, include=FALSE}

remittance_inflows <- read_excel("data/remittance_inflows.xlsx", skip = 0) %>%
  select(-c("Remittances as a share of GDP in 2019 (%)")) %>%
  melt(id.vars = "Migrant remittance inflows (US$ million)") %>%
  mutate(year = as.numeric(variable) + 1979) %>%
  clean_names() %>%
  select(-c(variable))

remittance_inflows <- inner_join(name_country, remittance_inflows,
                                 by = c("country_name" = "migrant_remittance_inflows_us_million"))

names(remittance_inflows) <- c("country", "inflows in millions of usd", "year")
  

# full_data <- full_data %>%
#   inner_join(remittance_inflows, by = c("country_name" = "migrant_remittance_inflows_us_million"))

# <- data[ -c(19:22) ] %>%
# na.omit()

```

```{r bilateral remittance 2010, include=FALSE}

brf_2010 <- read_excel("data/BilateralRemittanceMatrix2010.xlsx", skip = 1) %>% 
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2010)

names(brf_2010) <- c("sender", "recipient", "amount", "year") 

brf_2010 <- inner_join(name, brf_2010, by = "sender")

```

```{r bilateral remittance 2011, include = FALSE}

brf_2011 <- read_excel("data/BilateralRemittanceMatrix2011.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2011)

names(brf_2011) <- c("sender", "recipient", "amount", "year") 

brf_2011 <- inner_join(name, brf_2011, by = "sender")

```

```{r bilateral remittance 2012, include=FALSE}

brf_2012 <- read_excel("data/BilateralRemittanceMatrix2012.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2012)

names(brf_2012) <- c("sender", "recipient", "amount", "year") 

brf_2012 <- inner_join(name, brf_2012, by = "sender")

```

```{r bilateral remittance 2013, include=FALSE}

brf_2013 <- read_excel("data/BilateralRemittanceMatrix2013.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2013)

names(brf_2013) <- c("sender", "recipient", "amount", "year") 

brf_2013 <- inner_join(name, brf_2013, by = "sender")

```


```{r bilateral remittance 2014, include=FALSE}

brf_2014 <- read_excel("data/BilateralRemittanceMatrix2014.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2014)

names(brf_2014) <- c("sender", "recipient", "amount", "year") 

brf_2014 <- inner_join(name, brf_2014, by = "sender")

```

```{r bilateral remittance 2015, include=FALSE}

brf_2015 <- read_excel("data/BilateralRemittanceMatrix2014.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2015)

names(brf_2015) <- c("sender", "recipient", "amount", "year") 

brf_2015 <- inner_join(name, brf_2015, by = "sender")

```

```{r bilateral remittance 2016, include=FALSE}

brf_2016 <- read_excel("data/bilateralremittancematrix2016.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2016)

names(brf_2016) <- c("sender", "recipient", "amount", "year") 

brf_2016 <- inner_join(name, brf_2016, by = "sender")

```

```{r bilateral remittance 2017, include=FALSE}

brf_2017 <- read_excel("data/bilateralremittancematrix2017.xlsx", skip = 1) %>%
  melt(id.vars = "Remittance-receiving country (across)                                                              -                                                 Remittance-sending country (down)") %>%
  mutate(year = 2017)

names(brf_2017) <- c("sender", "recipient", "amount", "year") 

brf_2017 <- inner_join(name, brf_2017, by = "sender")

brf_2017

```

```{r rbind, include=FALSE}
all_bilateral_remittance <- rbind(brf_2010, brf_2011, brf_2012, brf_2013, brf_2014, brf_2015, brf_2016, brf_2017)
```



