---
title: "Loading/Cleaning"
author: "Vivian Zhang"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(shiny)
library(shinythemes)
library(plotly)
library(readxl)
library(janitor)
library(rvest)
library(magrittr)
library(base)
library(reshape2)
library(leaflet)
library(sp)
library(maptools)
library(maps)
library(gt)
library(broom)
library(tidyverse)

data(wrld_simpl)

```

```{r}

# In this Rmd document, I clean all my data. The app.R script is where I
# turn everything into a shiny app, create my maps/plots, etc.

#---------------------------------------------------------------------
#----------------------EU Facts Scraped from Online-------------------

eumemberinfo <- read_html('https://en.wikipedia.org/wiki/Member_state_of_the_European_Union', skip = 0) %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table[5]') %>%
  html_table()

eumemberinfo <- eumemberinfo[[1]]

# Select only the first four numbers to get the accession year

eumemberinfo$Accession <- substr(eumemberinfo$Accession, 0, 4)

# Add the United Kingdom

eumemberinfo <- rbind(eumemberinfo, c("United Kingdom", 1990))

# Only interested in the first two columns

eumemberinfo <- eumemberinfo[,c(1:2)]

# Removing Wikipedia annotations

eumemberinfo$Name <- str_remove_all(eumemberinfo$Name, "\\[.*\\]")

# Changing the names because Eastern European countries are labeled
# differently on the two datasets

eumemberinfo$Name[eumemberinfo$Name == "Czechia"] <- "Czech Republic"

eumemberinfo$Name[eumemberinfo$Name == "Slovak Republic"] <- "Slovakia"

# Getting a list of eunames by pulling from the Name column

eunames <- eumemberinfo %>%
   pull(Name)

mychoices <- eumemberinfo %>%
  select(Name) %>%
  arrange()

# Filtering wrld_simpl for just EU member states

wrld_simpl_data <- wrld_simpl[which(wrld_simpl@data$NAME %in% eunames), ]

target_order <- wrld_simpl_data@data$NAME

# Reordering my eumemberinfo dataframe to match wrld_simpl_data
# Prevents countries from being mislabeled

eumemberinfo <- eumemberinfo[match(target_order, eumemberinfo$Name), ]

name <- eumemberinfo %>%
  select(Name)

names(name) <- c("sender")

#-------------------------------------------------------------------
#----------------------Remittances in USD---------------------------

# Load remittances in USD in a given country, in alphabetical order

usd_inflows <- read_excel("shiny/data/april2020_remittanceinflows.xlsx", skip = 0)

# Pivot longer to have an observation for each year

usd_inflows <- usd_inflows %>%
  pivot_longer(
    cols = `2000`:`2018`,
    names_to = "year",
    names_prefix = "yr"
  ) %>%
  clean_names() %>%
  rename("country_name" = migrant_remittance_inflows_us_million)

# Deleting unnecessary columns

usd_inflows <- usd_inflows[,-c(2:23)]

# Change mismatched name

usd_inflows$country_name <- gsub('Slovak Republic', 'Slovakia',
                               usd_inflows$country_name)

# Join data into larger full_data dataframe

full_data <- usd_inflows %>%
  right_join(eumemberinfo, by = c("country_name" = "Name")) %>%
  rename(remittances_in_usd = value) %>%
  clean_names %>%
  filter(country_name %in% name$sender)

# Load remittances as percentage of GDP for a given country

percent_gdp <- read_excel("shiny/data/remittance_percentgdp.xls", skip = 2)

# Fixing naming differences before merging data

percent_gdp$`Country Name` <- gsub('Slovak Republic', 'Slovakia',
                               percent_gdp$`Country Name`)

# Pivoting longer again for annual observation

percent_gdp <- percent_gdp %>%
  pivot_longer(
    cols = `2000`:`2018`,
    names_to = "year",
    names_prefix = "yr") %>%
  rename("remittances_percent_gdp" = value) %>%
  clean_names %>%
  filter(country_name %in% name$sender)

# Deleting unnecessary columns

percent_gdp <- percent_gdp[,-c(2:45)]

# Join this with the previous data and select only the relevant columns

full_data <- full_data %>%
  left_join(percent_gdp, by = c("country_name"="country_name", "year"="year"), suffix = c("_usd", "_gdp")) %>%
  select(country_name, accession, year, remittances_in_usd, remittances_percent_gdp)

# Loading remittance outflow data

remittance_outflows <- read_excel("shiny/data/remittance_outflow_april2020.xlsx", skip = 0)

# Fixing unmatched names

remittance_outflows$`Migrant remittance outflows (US$ million)` <- gsub('Slovak Republic', 'Slovakia', remittance_outflows$`Migrant remittance outflows (US$ million)`)

# Pivot longer for annual observations for each EU member state

remittance_outflows <- remittance_outflows %>%
  pivot_longer(
    cols = `2000`:`2018`,
    names_to = "year",
    names_prefix = "yr"
  ) %>%
  clean_names() %>%
  rename("country_name" = migrant_remittance_outflows_us_million)

# Delete unnecessary columns

remittance_outflows <- remittance_outflows[,-c(2:22)]

# Merging data and selecting columns we are interested in

full_data <- full_data %>%
  left_join(remittance_outflows, by = c("country_name"="country_name", "year"="year")) %>%
  rename(remittances_outflows = value) %>%
  select(country_name, accession, year, remittances_in_usd, remittances_percent_gdp, remittances_outflows)

# Setup for ggplot of Remittances in USD

mydata <- full_data %>%
  na.omit %>%
  group_by(year,accession) %>%
  summarize(sum_remittance_usd = sum(remittances_in_usd)) %>%
  ungroup() %>%
  mutate(year = as.numeric(as.character(year)))

# Saving my data as RDS files, which I will then load into app.R

saveRDS(object = full_data,file = "shiny/full_data.rds")

saveRDS(object = mychoices,file = "shiny/mychoices.rds")

saveRDS(object = eunames,file = "shiny/eunames.rds")

```