---
title: "ms_4.Rmd"
author: "Vivian Zhang"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MS4 Updates on Final Project

This was a busy week with lots of midterms, but I visited the ARC to ask about tips for the final project. I learned that I could find a link to everyone's githubs from previous years on the about pages on their project websites. In particular, this map of Latin America interests me. I want to display remittance inflows and outflows by having a button on top of each country that allows the user to click and see how much inflow or outflow there was (https://igormorzan.shinyapps.io/Latin_American_Corruption/). I spent a lot of time exploring a dozen projects and emailed a couple of people from the World Bank asking for more demographic data on EU remittances specifically. I am really interested in the age range, gender, etc. of migrant workers sending remittances to their home countries from the EU (and the UK). I cleaned my code for bilateral remittances (I loaded and cleaned data from about eleven sources last week, so I have plenty of data to work with and rearrange). This weekend, I plan to work with the data and place the data on a map of the world.
