---
title: "test"
author: "Vivian Zhang"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(shiny)
library(shinythemes)
library(plotly)
library(readxl)
library(janitor)
library(rvest)
library(magrittr)
library(base)
library(reshape2)
library(leaflet)
library(sp)
library(maptools)
library(maps)

library(tidyverse)

data(wrld_simpl)

label = ~paste0("Country: ", wrld_simpl_data@data$NAME, ", ",
                  #                 "Total Remittances: $", 
                  #                 round(pal_val,0), 
                  #                 " Mln", sep=""),
                  # labelOptions = labelOptions(
                  #   style = list("font-weight" = "normal", padding = "3px 8px"),
                  #   textsize = "12px",
                  #   direction = "auto"),
                  # highlight = highlightOptions(weight = 3, color = "white", bringToFront = TRUE)) %>%

 
  # output$value <- renderPrint({ full_data$year })
  
  # output$inflows <- renderLeaflet({
  #   
  #   full_data$year <- as.numeric(input$year_inflows)
  #   
  #   leaflet(wrld_simpl_data, options = leafletOptions(dragging = TRUE,
  #                                                     minZoom = 3,
  #                                                     maxZoom = 6)) %>%
  #     addProviderTiles("CartoDB") %>%
  #     setView(30, 55, 3) %>%
  #     addPolygons(weight = 2,
  #                 opacity = 1,
  #                 fillColor = ~pal(full_data$remittances_in_usd),
  #                 fillOpacity = 1,
  #                 color = "black",
  #                 label = ~paste0("Country: ", wrld_simpl_data@data$NAME, ", ",
  #                                 "Total Remittances: $", round(full_data$remittances_in_usd,0), " Mln", sep=""),
  #                 labelOptions = labelOptions(
  #                   style = list("font-weight" = "normal", padding = "3px 8px"),
  #                   textsize = "12px",
  #                   direction = "auto"
  #                 ),
  #                 highlight = highlightOptions(weight = 3, color = "white", bringToFront = TRUE)) %>%
  #     addLegend(pal = pal, values = ~full_data$remittances_in_usd, opacity = 0.7,
  #               title = "Remittances in Millions of USD", position = "bottomright") %>%
  #     setMaxBounds(lng1 = 15, lat1 = 35, lng2 = 20, lat2 = 70)
  # })
  

## PART ONE: DATA WRANGLING

#---------------------------------------------------------------------
#----------------------EU Facts Scraped from Online-------------------

eumemberinfo <- read_html('https://en.wikipedia.org/wiki/Member_state_of_the_European_Union', skip = 0) %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table[5]') %>%
  html_table()

eumemberinfo <- eumemberinfo[[1]]

# Removing Wikipedia annotations

eumemberinfo$Name <- str_remove_all(eumemberinfo$Name, "\\[.*\\]")

# Select only the first four numbers to get the accession year

eumemberinfo$Accession <- substr(eumemberinfo$Accession, 0, 4)

# Changing the names because Eastern European countries are labeled
# differently on the two datasets

eumemberinfo$Name[eumemberinfo$Name == "Czechia"] <- "Czech Republic"

eumemberinfo$Name[eumemberinfo$Name == "Slovakia"] <- "Slovak Republic"

name <- eumemberinfo %>%
  select(Name)

names(name) <- c("sender")

#-------------------------------------------------------------------
#----------------------Remittances in USD---------------------------

# Load remittances in USD in a given country, in alphabetical order

usd <- read_excel("shiny/data/remittances_usd.xls", skip = 2)

# Trying to get rid of the x in front of the data
# Filter to only show between 1980 to present
# Repeatedly getting the error that argument "pattern" is missing, with no
# default
# Convert USD to Euros - maybe later

usd <- usd %>%
  pivot_longer(
    cols = `1980`:`2018`,
    names_to = "year",
    names_prefix = "yr"
  )

usd <- usd[,-c(5:25)]

# join this with the eumemberinfo to only look at member states

full_data <- usd %>%
  inner_join(eumemberinfo, by = c("Country Name" = "Name")) %>%
  rename(remittances_in_usd = value) %>%
  clean_names %>%
  filter(country_name %in% name$sender)

# Load remittances as percentage of GDP for a given country

percent_gdp <- read_excel("shiny/data/remittance_percentgdp.xls", skip = 2)

percent_gdp <- percent_gdp %>%
  pivot_longer(
    cols = `1980`:`2018`,
    names_to = "year",
    names_prefix = "yr") %>%
  rename(remittances_percent_gdp = value) %>%
  clean_names %>%
  filter(country_name %in% name$sender)

percent_gdp <- percent_gdp[,-c(5:25)]

# Join this with the previous data and select only the relevant columns

full_data <- full_data %>%
  inner_join(percent_gdp, by = c("country_name"="country_name", "year"="year"), suffix = c("_usd", "_gdp")) %>%
  select(country_name, country_code_usd, accession, year, remittances_in_usd, remittances_percent_gdp)

# Setup for ggplot of Remittances in USD

# mydata <- full_data %>%
#   na.omit %>%
#   group_by(year) %>%
#   summarize(sum_remittance_usd = sum(remittances_in_usd)) %>%
#   ungroup() %>%
#   mutate(year = as.numeric(as.character(year)))

# usd <- read_excel("shiny/data/remittances_usd.xls", skip = 2)

#source("shiny/data.R")

# Things to fix: change the labels and numbers for hovering results to be
# correct. Figure out how to load data properly on the data.R file and how to
# organize data for submission. Figure out how to get the chloropeth plot and
# what exactly to pipe in to have the wrld_simpl_data plot to show up on the
# shinyapp.

full_data$country_name <- gsub('Slovak Republic', 'Slovakia', full_data$country_name)

full_data <- full_data %>%
  filter(year == 2000)

target_order <- wrld_simpl_data@data$NAME

full_data <- full_data[match(target_order, full_data$country_name),]

# full_data$country_name <- reorder.factor(full_data$country_name, new.order=wrld_simpl_data@data$NAME)

# ordered_full_data <- wrld_simpl_data@data %>%
#   inner_join(full_data, by = c("NAME" = "country_name"))

# full_data <- full_data %>%
#   arrange(country_name)
# wrld_simpl_data@data$NAME <- wrld_simpl_data@data$NAME %>%
#   arrange(NAME)
# test2 <- full_data[full_data$country_name %in% test & full_data$year == 2000, ]
# colnames(test2)[1] <- 'NAME'
# test3 <- merge.data.frame(wrld_simpl_data@data, test2, 'NAME')
# wrld_simpl_data@data <- test3

# Join remittance data to the country data
# Left_join

wrld_simpl_data %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons(weight = 1,
              color = "blue",
              label = ~paste0("Country: ", wrld_simpl_data@data$NAME, ",\n",
                              "Total Remittances: $", full_data$remittances_in_usd, sep=""),
              highlight = highlightOptions(weight = 3, color = "red", bringToFront = TRUE))
  # colorNumeric(palette = "Blues",
  #              domain = log(wrld_simpl_data@data$remmitance_inflows))

load(url("http://spatial.nhh.no/R/etc/TM_WORLD_BORDERS_SIMPL-0.2.RData"))

# Arrange world simple first

data(world.cities)

world.cities$country.etc[world.cities$country.etc == "Czechia"] <- "Czech Republic"

world.cities$country.etc[world.cities$country.etc == "Slovakia"] <- "Slovak Republic"

eu_capitals <- world.cities %>%
  filter(capital == 1) %>%
  mutate(country = as.character(country.etc)) %>%
  inner_join(eumemberinfo, by = c("country" = "Name")) %>%
  select(country, long, lat) %>%
  filter(long != 33.38)

# To prepare for the next step, creating a list of EU member countries.

eumemberinfo$Name[eumemberinfo$Name == "Slovak Republic"] <- "Slovakia"

eunames <- eumemberinfo %>%
  pull(Name)

# Considers only the polygons for the EU countries.

wrld_simpl_data <- wrld_simpl[which(wrld_simpl@data$NAME %in% eunames), ]

# wrld_simpl_data@data <- wrld_simpl_data@data %>%
#   arrange(wrld_simpl_data@data$NAME)

# australia.map < - world.map[world.map$NAME == "Australia",]
# plot(australia.map)

#-----------------------------------------------------------------
#--------------------------Shiny ui-------------------------------

ui <- fluidPage(
  theme = shinytheme("flatly"),
  
  navbarPage(tags$b("EU Remittance Flows"),
             
             tabPanel("About",
                      imageOutput("global_remittance", width = "100%", 
                                  height = "100%"),
                      h1(tags$b("EU Remittance Flows"), align = "center"),
                      p(tags$em("Models of Remittance Inflows and Outflows over the last 40 years"),
                        align = "center"),
                      p("Welcome! This webpage looks at remittance flows in the EU from the 1980s to present.",
                        align = "center"),
                      h2(tags$b("Contact")),
                      p("Hi! I am Vivian Zhang, a first year at Harvard College studying Economics with a secondary in Government!"),
                      p("You can reach me at vivianzhang@college.harvard.edu."),
                      p("The code for this project can be accessed from",
                        a(href="https://github.com/VivianZ101055", "my github repository.")),
                      br(),
                      hr("Acknowledgements:"),
                      p("Thank you to Preceptor David Kane and all the members of GOV 1005 for introducing me to data science and helping me on this project!")
             ),
             
             tabPanel("Graphs",
                      sidebarLayout(
                        sidebarPanel(
                          h3("Interactive Graphs")
                        ),
                        mainPanel(
                          tabsetPanel(
                            tabPanel("Remittances in USD",
                                     plotlyOutput("distPlot"))
                            ),
                          tabsetPanel(
                            tabPanel("Remittances as a Percentage of GDP")
                          ),
                          tabsetPanel(
                            tabPanel("Case Study: UK")
                          )
                          )
                        )
                      ),
  
  navbarMenu("Remittance Maps",
             tabPanel("Inflows",
                      leaflet(wrld_simpl_data, options = leafletOptions(dragging = TRUE,
                                                       minZoom = 3,
                                                       maxZoom = 6)) %>%
                        addProviderTiles("CartoDB") %>%
                        setView(30, 55, 3) %>%
                        addCircleMarkers(lng = eu_capitals$long,
                                   lat = eu_capitals$lat,
                                   label = eu_capitals$country,
                                   radius = 5,
                                   color = "blue") %>%
                        addPolygons(weight = 1,
                                    color = "blue",
                                    label = ~paste0("Country: ", full_data$country_name, "\n",
                                                    "Total Remittances: ", full_data$remittances_in_usd),
                                    highlight = highlightOptions(weight = 3, color = "red", bringToFront = TRUE)) %>%
                        colorNumeric(palette = "Blues",
                                     domain = log(full_data$remittances_in_usd)) %>%
                        setMaxBounds(lng1 = 15, lat1 = 35,
                                  lng2 = 20, lat2 = 70)),
             tabPanel("Outflows",
                      leaflet() %>%
                        addTiles() %>%
                        setView(30, 55, 3)))
  ))

#-----------------------------------------------
#--------------------Server---------------------

server <- function(input, output){
  
  output$global_remittance <- renderImage({
    list(src = "shiny_files/remittances.png",
         height = 300,
         width = 600,
         style = "display: block; margin-left: auto; margin-right:auto")
  }, deleteFile = FALSE
  )
  
  output$distPlot <- renderPlotly({
    p <- ggplot(mydata, aes(x = year, y = sum_remittance_usd)) +
      geom_line(color = "light blue") +
      geom_point(aes(text = 
                       paste0("Year: ", year, "\n", 
                              "Total Remittances: $",
                              round(sum_remittance_usd/1000000000,0),
                              "B", sep="")), color = "dark blue") +
      labs(title = "Total remittances flowing into the EU, by year",
           x = "Year",
           y = "Total Remittances (in Billions of USD)") +
      scale_x_continuous(limits = c(1980, 2018),
                         breaks = c(1980, 1985, 1990, 1995, 2000, 2005, 2010,
                                    2015),
                         labels = c("1980", "1985", "1990", "1995",
                                    "2000", "2005", "2010",
                                    "2015")) +
      scale_y_continuous(limits = c(0, 120000000000),
                         breaks = c(0, 10000000000, 20000000000, 30000000000,
                                    40000000000, 50000000000, 60000000000,
                                    70000000000, 80000000000, 90000000000,
                                    100000000000, 110000000000, 120000000000),
                         labels = c("0", "10", "20", "30", "40", "50", "60", "70", "80",
                                    "90", "100", "110", "120")) +
      theme_classic()
    
    # Generates the plot with text hovering feature
    
    ggplotly(p, tooltip = "text")
    
    })
}

shinyApp(ui = ui, server = server)
